### ISSUE TITLE
how can I make it work?

### ISSUE THREAD

**Issue by Geniusssmit** [Derrick56007/getsub#1]
I have that issue
```
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from get_sub import GetSub
  File "src\get_sub.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by derrick56007** [comment]
pandas is a requirement, try installing it using pip first

**Comment by derrick56007** [comment]
Let me know if you have any further issues
